services:
  tiktok-carousel:
    container_name: tiktok-carousel
    build: .
    ports:
      - "8989:3000"
    env_file:
      - .env
    networks:
      - database_default
    
networks:
  database_default:
    external: true